In [ ]:
!wandb login

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit: 
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: sai-sakunthala (sai-sakunthala-indian-institute-of-technology-madras) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin


In [ ]:
from keras.datasets import fashion_mnist
import wandb
import numpy as np
import math
import random

In [ ]:
wandb.init(
    # set the wandb project where this run will be logged
    project="Fashion-mnist", name = "Images")

wandb: Currently logged in as: sai-sakunthala (sai-sakunthala-indian-institute-of-technology-madras) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.


In [ ]:
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()
class_names = ['Tshirt', 'Trouser', 'Pullover', 'Dress', 'Coat', 'Sandal', 'Shirt', 'Sneaker', 'bag', 'Ankleboot']

one_per_label = {}
for image,label in zip(x_train,y_train):
    if label not in one_per_label:
        one_per_label[label] = image

29515/29515 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
26421880/26421880 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
5148/5148 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
4422102/4422102 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [ ]:
for label, image in one_per_label.items():
    wandb.log({"Images": [wandb.Image(image, caption=class_names[label])]})

In [ ]:
def input_layer(x):
    x = np.array(x)
    a,b,c = x.shape
    x = x.reshape(a,b*c)
    return x

def sigmoid(a_x):
    h_x = np.zeros(len(a_x))
    for i in range(len(a_x)):
        h_x[i] = 1/(1+math.exp(-a_x[i]))
    return h_x

def der_sigmoid(a_x):
    del_sig = np.zeros(len(a_x))
    for i in range(len(a_x)):
        del_sig[i] = a_x[i]*(1-a_x[i])
    return del_sig

def Relu(a_x):
    h_x = np.zeros(len(a_x))
    for i in range(len(a_x)):
        h_x[i] = max(0,a_x[i])
    return h_x

def der_Relu(a_x):
    del_Relu = np.zeros(len(a_x))
    for i in range(len(a_x)):
        if a_x[i] > 0:
            del_Relu[i] = a_x[i]
        else:
            del_Relu[i] = 0
    return del_Relu

def tanh(a_x):
    h_x = np.zeros(len(a_x))
    for i in range(len(a_x)):
        h_x[i] = (math.exp(a_x[i]) - math.exp(-a_x[i]))/(math.exp(a_x[i]) + math.exp(-a_x[i]))
    return h_x

def der_tanh(a_x):
    del_tanh = np.zeros(len(a_x))
    for i in range(len(a_x)):
        del_tanh[i] = 1 - [(math.exp(a_x[i]) - math.exp(-a_x[i]))/(math.exp(a_x[i]) + math.exp(-a_x[i]))]**2
    return del_tanh

def softmax(a_x):
    h_x = np.zeros(len(a_x))
    for i in range(len(a_x)):
        h_x[i] = math.exp(a_x[i])
    h_x = h_x/np.sum(h_x)
    return h_x

def der_softmax(a_x):
    del_softmax = np.zeros(len(a_x))
    for i in range(len(a_x)):
        del_softmax[i] = a_x[i]*(1-a_x[i])

def initialize_weights(num_neurons):
    weights = []
    biases = []
    for i in range(len(num_neurons) - 1):
        W = np.random.randn(num_neurons[i], num_neurons[i+1])
        b = np.random.randn(1, num_neurons[i+1])
        weights.append(W)
        biases.append(b)
    return weights, biases

def pre_activation(h_x, W, b):
    a_x = np.dot(h_x, W) + b
    return a_x

def loss_function(h_x, y):
    idx = np.where(y == 1)
    loss = -np.log(h_x[idx])
    return loss

def forward_pass(x, y, weights, biases, activation_func, n_hidden):
    activations = []
    pre_activations = []
    for i in range(n_hidden+2):
        if i == 0:
            a_x = pre_activation(x, weights[i], biases[i])
            print(a_x)
            h_x = activation_func(a_x)
            activations.append(h_x)
            pre_activations.append(a_x)
        elif i == n_hidden + 1:
            a_x = pre_activation(h_x, weights[i], biases[i])
            h_x = softmax(a_x)
            activations.append(h_x)
            pre_activations.append(a_x)
        else:
            a_x = pre_activation(h_x, weights[i], biases[i])
            h_x = activation_func(a_x)
            activations.append(h_x)
            pre_activations.append(a_x)
    loss = loss_function(h_x, y)
    return np.array(activations), np.array(pre_activations), loss

a,b = forward_pass(np.array([[1,1],[0,0],[1,1],[2,2]]), np.array([0,1,0,2]), initialize_weights([2,3,3,2])[0], initialize_weights([2,3,3,2])[1], sigmoid, 2)
print(a,b)

def one_hot_encode(y, num_classes):
    return np.eye(num_classes)[y]

def back_propagation(activations, pre_activations, weights, biases, y, y_hat, n_hidden, activation_deriv):
    del_L_a = {}
    del_L_w = {}
    del_L_b = {}
    del_L_h = {}
    for i in range(n_hidden+1, 0, -1):
        if i == n_hidden + 1:
            del_L_a[i] = -(y - y_hat)
        del_L_w[i] = np.dot(activations[i-1].T, del_L_a[i])
        del_L_b[i] = del_L_a[i]
        del_L_h[i-1] = np.matmul(del_L_a[i], weights[i-1].T)
        del_L_a[i-1] = np.multiply(del_L_h[i-1], activation_deriv(pre_activations[i-1]))

def Neuralnet(x_train, y_train, n_hidden, n_neurons_hidden, epochs, batch_size, activation):
    x_train = input_layer(x_train)
    y_train = one_hot_encode(y_train, len(np.unique(y_train)))
    features = x_train.shape[1]
    classes = len(np.unique(y_train))
    num_neurons = [features] + [n_neurons_hidden]*(n_hidden) + [classes]
    weights, biases = initialize_weights(num_neurons)
    activation_func = {"sigmoid": sigmoid, "tanh": tanh, "relu": Relu}[activation]
    activation_deriv = {"sigmoid": der_sigmoid, "tanh": der_tanh, "relu": der_Relu}[activation]
    #epochs
    for epoch in range(epochs):
        for i in range(0, len(x_train), batch_size):
            x_batch = x_train[i:i + batch_size]
            y_batch = y_train[i:i + batch_size]
            for x,y in zip(x_batch,y_batch):
                activations, pre_activations, loss = forward_pass(x, y, weights, biases, activation_func, n_hidden)

#Neuralnet(np.array([[1,1],[0,0],[1,1],[2,2]]), np.array([0,1,0,2]), 2, 3, 10, 2, 'sigmoid')

[[-1.60171371  0.00999735  3.22795799]
 [-1.54355062  1.12178756  1.39189888]
 [-1.60171371  0.00999735  3.22795799]
 [-1.65987681 -1.10179286  5.0640171 ]]


TypeError: only length-1 arrays can be converted to Python scalars

In [ ]:
print(np.dot(np.array([[1,2]]).T, np.array([[3,4]])))

[[3 4]
 [6 8]]
